# vim: set filetype=yaml.ansible:
---
- name: Install tools
  hosts:
    - localhost
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name:
          - apt-file
          - btop
          - htop
          - locate
          - lsof
          - nano
          - vim
        state: present
        update_cache: true

- name: Lock down box
  become: true
  tags:
    - security
    - prison
  hosts:
    - localhost
  roles:
    - geerlingguy.security
  vars_files:
    - vars/security.yml

- name: Setup SSH Prison
  become: true
  tags:
    - prison
  hosts:
    - localhost
  roles:
    - geerlingguy.ssh-chroot-jail
  vars_files:
    - vars/prison.yml
