# vim: set filetype=yaml.ansible:
---
- name: Setup box
  hosts:
    - localhost
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name:
          - apt-file
          - btop
          - ed
          - htop
          - locate
          - lsof
          - nano
          - vim
        state: present
        update_cache: true
    - name: Ensure user
      become: true
      ansible.builtin.user:
        name: dingus
        state: present
        groups:
          - sudo
        create_home: true
        home: /home/dingus
        shell: /bin/bash
        comment: Meow

- name: Lock down box
  become: true
  tags:
    - security
    - prison
  hosts:
    - localhost
  roles:
    - geerlingguy.security
  vars_files:
    - vars/security.yml

- name: Setup SSH Prison
  become: true
  tags:
    - prison
  hosts:
    - localhost
  roles:
    - geerlingguy.ssh-chroot-jail
  vars_files:
    - vars/prison.yml

- name: Ensure firewall
  become: true
  tags:
    - firewall
  hosts:
    - localhost
  roles:
    - geerlingguy.firewall
  vars_files:
    - vars/firewall.yml
# Any additional tasks can go below here
